source "http://rubygems.org"

ruby "2.3.3"

gem "rails", "~> 4.2.5"
gem "rails-api"
gem "sqlite3"
gem "better_errors"
gem "dotenv-rails"
gem "sidekiq"
gem "devise_token_auth"
gem "resque"
gem "resque-status"
gem "nokogiri", "1.6.8.1"